FROM golang:latest AS builder

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update; apt-get -y install ca-certificates

COPY . /go/src/github.com/fioprotocol/fio.etl
WORKDIR /go/src/github.com/fioprotocol/fio.etl

RUN go build -race -ldflags "-s -w" -o /consumer cmd/fioetl-consumer/main.go


### just a source for SSL libraries, golang:latest has a lot installed.
FROM debian:10 AS ssl
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update; apt-get -y upgrade && apt-get install -y ca-certificates


### try to build a lighter container
FROM scratch
COPY --from=builder /consumer /consumer
COPY auth.yml /
# this gets libssl1.1, openssl, and libc6 which we need for TLS, not tiny, but saves about 1 GiB in final image size
COPY --from=ssl /etc/ca-certificates /etc/ca-certificates
COPY --from=ssl /etc/ssl /etc/ssl
COPY --from=ssl /usr/share/ca-certificates /usr/share/ca-certificates
COPY --from=ssl /usr/lib /usr/lib
COPY --from=ssl /lib /lib
COPY --from=ssl /lib64 /lib64

USER 65535
CMD ["/consumer"]

