version: '3.8'
services:

  chronicle:
    build: dist/chronicle
    volumes:
      - type: volume
        source: chronicle-data
        target: /opt/data
    environment:
      - DATA_DIR=./data
      - MODE=scan
      - HOST=<**your history node here**> #ip address or hostname of nodeos with state-history plogin
      - PORT=8080 #port number of state history plugin
      - WS_HOST=fioetl
      - WS_PORT=8844
      - SKIP_BLOCK_EVENTS=false
      - SKIP_TABLE_DELTAS=false
      - SKIP_TRACES=false
      - BIN_HEADER=false
      - EXP_WS_PATH=/chronicle
      - EXP_WS_MAX_QEUEU=10000
      - IRREVERSIBLE_ONLY=true
    restart: always
    stop_grace_period: 1m30s
    depends_on:
      - fioetl

  fioetl-producer:
    build:
      context: .
      dockerfile: Dockerfile-publisher
    restart: always
    stop_grace_period: 1m30s
    depends_on:
      - rabbit

  fioetl:
    build:
      context: .
      dockerfile: Dockerfile-consumer
    expose:
      - "8844"
    restart: always
    environment:
      - HOST=<**your history node here**> #ip address or hostname of nodeos
      - FALLBACK_PORT=8888 #port number for chain_plugin API, used only if an error getting block id from hash of block header
    stop_grace_period: 1m30s
    depends_on:
      - rabbit

  rabbit:
    image: "rabbitmq:latest"
    restart: always
    stop_grace_period: 1m30s
    volumes:
      - type: volume
        source: rabbit-data
        target: /var/lib/rabbitmq
    expose:
      - "5672"

volumes:
  chronicle-data:
  rabbit-data:
